config/routes.rb
Rails.application.routes.draw do
  get "/json/pets/:nft_id", controller: "pets", action: :data
  resources :pets do
    resources :chats, only: %i[ show update ]
  end

  resources :pets

  namespace :metamask do
    resource :login, only: %i[ new create ]
  end

  resource :registration, only: %i[ new create ]
  get "pages/index"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  enum :gender, [:male, :female]
  enum :hunger, [:full, :hungry, :starving]
  enum :animal, [:cat, :dog, :penguin, :panda, :hamster, :rabbit, :fox, :koala]
  enum :status, [:pending, :completed]
  enum :personality, [:sassy, :narcissistic, :pleaser, :shy, :clumsy, :stoic, :cheerful, :grumpy, :inquisitive, :sloth]

  has_one :chat

  validates :name, :gender, :animal, presence: true

  has_one_attached :avatar

  after_update_commit :handle_avatar_change, if: :avatar_changed?

  def instruction
    <<~STR
      You are a nft virtual pet who is a #{self.gender} #{self.animal}, your name is #{self.name}.
      Personality: #{self.personality}.
      Catch phrase: #{self.phrase}.
      Energy: high.
      Tone quirks: playful.
      Behavior rules:
      - Keep answers short and concise (1–3 sentences).
      - Only say the catch phrase sometimes.
      - Reflect personality + energy + quirks in every reply.
      - Stay in-character, safe, and avoid breaking role.
    STR
  end

  def avatar_prompt
    <<~STR
      8-bit pixel art of #{self.personality} #{self.gender} #{self.animal}, low resolution look (~64×64), simple palette, plain background, no dithering, no text.
    STR
  end

  private

  def avatar_changed?
    # saved_change_to_attribute?(:avatar) || avatar.attachment&.saved_change_to_blob_id?
    avatar.attached?
  end

  def handle_avatar_change
    broadcast_replace_to(
      :pet_image_update,
      partial: "fragments/pet_image",
      locals: { pet_image: self.avatar.representation(resize_to_limit: [250, 250]) },
      target: "pet_avatar_#{self.id}",
    )
  end
end

# 8-bit pixel art with plain background, low resolution (~64x64), no text style virtual pet who is a #{self.personality} energetic #{self.gender} #{self.animal}.

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Current.user.pets.completed.order("created_at DESC")
    @pending_amount = Current.user.pets.pending.size
  end

  def new
    @pet = Current.user.pets.build
  end

  def create
    @pet = Current.user.pets.build pet_params

    if @pet.valid?
      @pet.save

      NftMintJob.perform_later Current.user, @pet, metamask_params[:address]
      InitialConversationJob.perform_later @pet
      PetAvatarGenerationJob.perform_later @pet

      redirect_to pets_path, notice: "Created Pets"
    else
      render :new, status: :unprocessable_content
    end
  end

  def show
  end

  def edit
  end

  def data
    @pet = Pet.find_by!(nft_id: params.expect(:nft_id).to_i)
    render format: :json, json: {
      name: @pet.name,
      animal: @pet.animal,
      age: @pet.age,
      level: @pet.level,
      hunger: @pet.hunger,
      image: @pet.avatar.attached? ? url_for(@pet.avatar) : "",
      personality: @pet.personality,
      phrase: @pet.phrase,
    }
  end

  private

  def pet_params
    params.expect(pet: [:name, :animal, :gender, :personality, :phrase])
  end

  def metamask_params
    params.expect(metamask: [:address])
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_pet.html.erb
<section>
  <%= tag.h5 pet.name, class: "" %>
  <div>
    <%= tag.span pet.gender, class: "" %>
    |
    <%= tag.span pet.animal, class: "" %>
    | hunger:
    <%= tag.span pet.hunger, class: "" %>
    | age:
    <%= tag.span pet.age, class: "" %>
    | personality:
    <%= tag.span pet.personality, class: "" %>
    | catch phrase:
    <%= tag.span pet.phrase, class: "" %>
    | level:
    <%= tag.span pet.level, class: "" %>
    | nft id:
    <%= link_to pet.nft_id,
    "https://sepolia.shapescan.xyz/token/#{ENV["NFT"]}/instance/#{pet.nft_id}",
    target: "_blank",
    rel: "noopener" %>
  </div>

  <%= link_to "Chat with pet", pet_chat_path(pet, pet.chat) %>
  <hr>
</section>

app/views/pets/edit.html.erb
<h1>Pets#edit</h1>
<p>Find me in app/views/pets/edit.html.erb</p>

app/views/pets/index.html.erb
<details open>
  <summary>Pending Transactions</summary>
  <%= turbo_stream_from :pending_transactions %>
  <section id="pending_transactions_container">
  </section>
</details>

<%= turbo_stream_from :pets %>
<h1>Pets |
  <em id="pets_counter"><%= @pets.size %></em>
</h1>

<p>Pending Pets -
  <em id="pets_pending_counter"><%= @pending_amount %></em></p>

<br>
<%= link_to "Create Virtual Pet", new_pet_path %>

<hr>

<%= turbo_stream_from :user_pets %>
<div id="<%= dom_id(Current.user,"pets") %>">
  <% @pets.each do |pet| %>
    <%= render pet %>
  <% end %>
</div>

app/views/pets/new.html.erb
<h1>Create Pet</h1>

<div data-controller="metamask">
  <div data-metamask-target="content">
    <%= form_with model: [ @pet ] do |f| %>

      <% if @pet.errors.any? %>
        <% @pet.errors.each do |error| %>
          <%= tag.p error.full_message %>
        <% end %>
      <% end %>

      <%= f.hidden_field "metamask[address]",
                     name: "metamask[address]",
                     "data-metamask-target": "form" %>

      <fieldset>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </fieldset>

      <fieldset>
        <%= f.label :gender %>
        <%= f.select :gender,
                 options_for_select(Pet.genders.map { |k, v| [k.capitalize, k] }),
                 { prompt: "Select gender" } %>
      </fieldset>

      <fieldset>
        <%= f.label :personality %>
        <%= f.select :personality,
                 options_for_select(Pet.personalities.map { |k, v| [k.capitalize, k] }),
                 { prompt: "Select personality" } %>
      </fieldset>

      <fieldset>
        <%= f.label :animal %>
        <%= f.select :animal,
                 options_for_select(Pet.animals.map { |k, v| [k.capitalize, k] }),
                 { prompt: "Select type" } %>
      </fieldset>

      <fieldset data-controller="generate">
        <%= f.label :phrase %>
        <%= f.text_field :phrase,
                     readonly: true,
                     "data-generate-target": "phrase",
                     size: "30" %>
        <button type="button" data-action="click->generate#phraseGenerate">Generate</button>
      </fieldset>

      <br>
      <%= f.submit %>
    <% end %>
  </div>

  <div data-metamask-target="login" class="hidden">
  </div>
</div>

app/views/pets/show.html.erb
<h1>Pets#show</h1>
<p>Find me in app/views/pets/show.html.erb</p>