config/routes.rb
Rails.application.routes.draw do
  get "/json/pets/:nft_id", controller: "pets", action: :data
  resources :pets do
    resources :chats, only: %i[ show update ]
  end

  resources :pets

  namespace :metamask do
    resource :login, only: %i[ new create ]
  end

  resource :registration, only: %i[ new create ]
  get "pages/index"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/chat.rb
class Chat < ApplicationRecord
  acts_as_chat

  # belongs_to :user, optional: true # Example
  belongs_to :pet
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_pet, only: %i[ update show ]
  before_action :set_chat, only: %i[ update show ]

  def show
    @messages = @chat.messages
    @conversations_length = @messages.where(role: :user).size
  end

  def update
    @chat.ask chat_params[:question]

    redirect_to pet_chat_path(@pet, @chat), notice: "Created Message"
  end

  private

  def set_pet
    @pet = Pet.find(params.expect(:pet_id))
  end

  def set_chat
    @chat = Chat.find(params.expect(:id))
  end

  def chat_params
    params.expect(chat: [:question])
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/show.html.erb
<h1>Chat With
  <%= @pet.name %></h1>

<%= turbo_stream_from :pet_image_update %>

<div id="pet_avatar_<%= @pet.id %>">
  <% if @pet.avatar.attached? %>
    <%= image_tag @pet.avatar.representation(resize_to_limit: [250, 250]) %>
    <%# render "fragments/pet_image", locals: { pet: @pet } %>
  <% else %>
    <p>avatar still generating...</p>
  <% end %>
</div>

<ul>
  <li>Personality -
    <%= @pet.personality %></li>
  <li>Gender -
    <%= @pet.gender %></li>
  <li>Phrase -
    <%= @pet.phrase %></li>
  <li>Hunger -
    <%= @pet.hunger %></li>
  <li>Age -
    <%= @pet.age %></li>
  <li>Level -
    <%= @pet.level %></li>
  <li>Conversation Length -
    <%= @conversations_length %></li>
</ul>

<main style="width:50%">
  <fieldset>
    <% if @messages.any? %>
      <% @messages.each do |message| %>

        <% if message.role == "user" %>
          <p style="text-align: right;">
            <i>
              <%= tag.mark message.content %>
            </i>
          </p>
        <% end %>

        <% if message.role == "assistant" %>
          <p style="text-align: left;">
            <%= tag.i "#{@pet.name}: #{message.content}" %>
          </p>
        <% end %>

        <% if message.role == "assistant" %>
        <% end %>

      <% end %>
    <% end %>
  </fieldset>

  <%= form_with model: @chat, url: pet_chat_path(@pet) do |f| %>
    <fieldset>
      <%= f.text_field :question, style: "width:90%" %>
      <%= f.submit "Send" %>
    </fieldset>
  <% end %>
</main>

<%= link_to "Go Back", pets_path %>